# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RGISMainActivity.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RGISMain(object):
    def setupUi(self, RGISMain):
        RGISMain.setObjectName("RGISMain")
        RGISMain.resize(1308, 767)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RGISMain.sizePolicy().hasHeightForWidth())
        RGISMain.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(RGISMain)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.PlanName = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlanName.sizePolicy().hasHeightForWidth())
        self.PlanName.setSizePolicy(sizePolicy)
        self.PlanName.setMaximumSize(QtCore.QSize(151, 16777215))
        self.PlanName.setAlignment(QtCore.Qt.AlignCenter)
        self.PlanName.setWordWrap(True)
        self.PlanName.setObjectName("PlanName")
        self.verticalLayout.addWidget(self.PlanName)
        self.listPanelID = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listPanelID.sizePolicy().hasHeightForWidth())
        self.listPanelID.setSizePolicy(sizePolicy)
        self.listPanelID.setMinimumSize(QtCore.QSize(151, 621))
        self.listPanelID.setMaximumSize(QtCore.QSize(151, 16777215))
        self.listPanelID.setObjectName("listPanelID")
        self.verticalLayout.addWidget(self.listPanelID)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lab_projectName = QtWidgets.QLabel(self.centralwidget)
        self.lab_projectName.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_projectName.setObjectName("lab_projectName")
        self.verticalLayout_2.addWidget(self.lab_projectName)
        self.MapImage = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MapImage.sizePolicy().hasHeightForWidth())
        self.MapImage.setSizePolicy(sizePolicy)
        self.MapImage.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.MapImage.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.MapImage.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.MapImage.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.MapImage.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.MapImage.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.MapImage.setCacheMode(QtWidgets.QGraphicsView.CacheNone)
        self.MapImage.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorViewCenter)
        self.MapImage.setResizeAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.MapImage.setViewportUpdateMode(QtWidgets.QGraphicsView.BoundingRectViewportUpdate)
        self.MapImage.setRubberBandSelectionMode(QtCore.Qt.IntersectsItemShape)
        self.MapImage.setObjectName("MapImage")
        self.verticalLayout_2.addWidget(self.MapImage)
        self.te_bottom_hint = QtWidgets.QTextEdit(self.centralwidget)
        self.te_bottom_hint.setMaximumSize(QtCore.QSize(16777215, 60))
        self.te_bottom_hint.setObjectName("te_bottom_hint")
        self.verticalLayout_2.addWidget(self.te_bottom_hint)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setMinimumSize(QtCore.QSize(140, 0))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 141, 711))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.button_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.button_layout.setContentsMargins(0, 0, 0, 0)
        self.button_layout.setObjectName("button_layout")
        self.verticalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        RGISMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RGISMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1308, 18))
        self.menubar.setObjectName("menubar")
        self.menu66 = QtWidgets.QMenu(self.menubar)
        self.menu66.setObjectName("menu66")
        self.menu77 = QtWidgets.QMenu(self.menubar)
        self.menu77.setObjectName("menu77")
        RGISMain.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RGISMain)
        self.statusbar.setObjectName("statusbar")
        RGISMain.setStatusBar(self.statusbar)
        self.action_create_project = QtWidgets.QAction(RGISMain)
        self.action_create_project.setObjectName("action_create_project")
        self.action_history_project = QtWidgets.QAction(RGISMain)
        self.action_history_project.setObjectName("action_history_project")
        self.action_export_GPS_image = QtWidgets.QAction(RGISMain)
        self.action_export_GPS_image.setObjectName("action_export_GPS_image")
        self.action_import_GPS_image = QtWidgets.QAction(RGISMain)
        self.action_import_GPS_image.setObjectName("action_import_GPS_image")
        self.action_import_image = QtWidgets.QAction(RGISMain)
        self.action_import_image.setObjectName("action_import_image")
        self.action_gd_map = QtWidgets.QAction(RGISMain)
        self.action_gd_map.setObjectName("action_gd_map")
        self.menu66.addAction(self.action_create_project)
        self.menu66.addAction(self.action_history_project)
        self.menu77.addAction(self.action_export_GPS_image)
        self.menu77.addAction(self.action_import_GPS_image)
        self.menu77.addAction(self.action_gd_map)
        self.menubar.addAction(self.menu66.menuAction())
        self.menubar.addAction(self.menu77.menuAction())

        self.retranslateUi(RGISMain)
        QtCore.QMetaObject.connectSlotsByName(RGISMain)

    def retranslateUi(self, RGISMain):
        _translate = QtCore.QCoreApplication.translate
        RGISMain.setWindowTitle(_translate("RGISMain", "地理信息标注系统"))
        self.PlanName.setText(_translate("RGISMain", "面板列表"))
        self.lab_projectName.setText(_translate("RGISMain", "大地图"))
        self.groupBox.setTitle(_translate("RGISMain", "工具箱"))
        self.menu66.setTitle(_translate("RGISMain", "开始"))
        self.menu77.setTitle(_translate("RGISMain", "操作"))
        self.action_create_project.setText(_translate("RGISMain", "新建项目"))
        self.action_history_project.setText(_translate("RGISMain", "历史项目"))
        self.action_export_GPS_image.setText(_translate("RGISMain", "导出GPS/全景图"))
        self.action_export_GPS_image.setIconText(_translate("RGISMain", "导出GPS/全景图"))
        self.action_import_GPS_image.setText(_translate("RGISMain", "导入GPS/全景图"))
        self.action_import_image.setText(_translate("RGISMain", "导入全景图"))
        self.action_gd_map.setText(_translate("RGISMain", "高德地图显示"))
