# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_panel_info.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setPanelInfo(object):
    def setupUi(self, setPanelInfo):
        setPanelInfo.setObjectName("setPanelInfo")
        setPanelInfo.resize(498, 601)
        self.panel_model_5 = QtWidgets.QLabel(setPanelInfo)
        self.panel_model_5.setGeometry(QtCore.QRect(50, 330, 80, 21))
        self.panel_model_5.setObjectName("panel_model_5")
        self.panel_model_8 = QtWidgets.QLabel(setPanelInfo)
        self.panel_model_8.setGeometry(QtCore.QRect(50, 380, 80, 21))
        self.panel_model_8.setObjectName("panel_model_8")
        self.panel_model_19 = QtWidgets.QLabel(setPanelInfo)
        self.panel_model_19.setGeometry(QtCore.QRect(50, 430, 80, 21))
        self.panel_model_19.setObjectName("panel_model_19")
        self.panel_model_6 = QtWidgets.QLabel(setPanelInfo)
        self.panel_model_6.setGeometry(QtCore.QRect(50, 80, 80, 21))
        self.panel_model_6.setObjectName("panel_model_6")
        self.new_panel_model = QtWidgets.QLineEdit(setPanelInfo)
        self.new_panel_model.setGeometry(QtCore.QRect(190, 30, 251, 25))
        self.new_panel_model.setObjectName("new_panel_model")
        self.new_panel_arrange = QtWidgets.QLineEdit(setPanelInfo)
        self.new_panel_arrange.setGeometry(QtCore.QRect(190, 380, 251, 25))
        self.new_panel_arrange.setObjectName("new_panel_arrange")
        self.new_panel_wh = QtWidgets.QLineEdit(setPanelInfo)
        self.new_panel_wh.setGeometry(QtCore.QRect(190, 230, 251, 25))
        self.new_panel_wh.setObjectName("new_panel_wh")
        self.panel_model_2 = QtWidgets.QLabel(setPanelInfo)
        self.panel_model_2.setGeometry(QtCore.QRect(50, 180, 80, 21))
        self.panel_model_2.setObjectName("panel_model_2")
        self.new_label_type = QtWidgets.QComboBox(setPanelInfo)
        self.new_label_type.setGeometry(QtCore.QRect(190, 80, 251, 25))
        self.new_label_type.setObjectName("new_label_type")
        self.btu_new_close = QtWidgets.QPushButton(setPanelInfo)
        self.btu_new_close.setGeometry(QtCore.QRect(300, 490, 93, 28))
        self.btu_new_close.setObjectName("btu_new_close")
        self.panel_model_3 = QtWidgets.QLabel(setPanelInfo)
        self.panel_model_3.setGeometry(QtCore.QRect(50, 230, 80, 21))
        self.panel_model_3.setObjectName("panel_model_3")
        self.new_panel_angle = QtWidgets.QLineEdit(setPanelInfo)
        self.new_panel_angle.setGeometry(QtCore.QRect(190, 330, 251, 25))
        self.new_panel_angle.setObjectName("new_panel_angle")
        self.new_panel_color = QtWidgets.QWidget(setPanelInfo)
        self.new_panel_color.setGeometry(QtCore.QRect(350, 430, 91, 25))
        self.new_panel_color.setObjectName("new_panel_color")
        self.but_new_save = QtWidgets.QPushButton(setPanelInfo)
        self.but_new_save.setGeometry(QtCore.QRect(140, 490, 93, 28))
        self.but_new_save.setObjectName("but_new_save")
        self.panel_model_18 = QtWidgets.QLabel(setPanelInfo)
        self.panel_model_18.setGeometry(QtCore.QRect(50, 30, 80, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.panel_model_18.setFont(font)
        self.panel_model_18.setObjectName("panel_model_18")
        self.new_label_manufactor = QtWidgets.QLineEdit(setPanelInfo)
        self.new_label_manufactor.setGeometry(QtCore.QRect(190, 130, 251, 25))
        self.new_label_manufactor.setObjectName("new_label_manufactor")
        self.new_panel_altitude = QtWidgets.QLineEdit(setPanelInfo)
        self.new_panel_altitude.setGeometry(QtCore.QRect(190, 280, 251, 25))
        self.new_panel_altitude.setObjectName("new_panel_altitude")
        self.new_panel_power = QtWidgets.QLineEdit(setPanelInfo)
        self.new_panel_power.setGeometry(QtCore.QRect(190, 180, 251, 25))
        self.new_panel_power.setObjectName("new_panel_power")
        self.btn_panel_color = QtWidgets.QPushButton(setPanelInfo)
        self.btn_panel_color.setGeometry(QtCore.QRect(190, 430, 150, 25))
        self.btn_panel_color.setObjectName("btn_panel_color")
        self.panel_model_4 = QtWidgets.QLabel(setPanelInfo)
        self.panel_model_4.setGeometry(QtCore.QRect(50, 280, 80, 21))
        self.panel_model_4.setObjectName("panel_model_4")
        self.panel_model_7 = QtWidgets.QLabel(setPanelInfo)
        self.panel_model_7.setGeometry(QtCore.QRect(50, 130, 80, 21))
        self.panel_model_7.setObjectName("panel_model_7")
        self.setWindowModality(QtCore.Qt.ApplicationModal)
        self.retranslateUi(setPanelInfo)
        QtCore.QMetaObject.connectSlotsByName(setPanelInfo)

    def retranslateUi(self, setPanelInfo):
        _translate = QtCore.QCoreApplication.translate
        setPanelInfo.setWindowTitle(_translate("setPanelInfo", "设置组件信息"))
        self.panel_model_5.setText(_translate("setPanelInfo", "组件角度:"))
        self.panel_model_8.setText(_translate("setPanelInfo", "组件排布:"))
        self.panel_model_19.setText(_translate("setPanelInfo", "选择颜色:"))
        self.panel_model_6.setText(_translate("setPanelInfo", "标注类型:"))
        self.panel_model_2.setText(_translate("setPanelInfo", "组件功率:"))
        self.btu_new_close.setText(_translate("setPanelInfo", "取消"))
        self.panel_model_3.setText(_translate("setPanelInfo", "组件宽高:"))
        self.but_new_save.setText(_translate("setPanelInfo", "保存"))
        self.panel_model_18.setText(_translate("setPanelInfo", "组件型号:"))
        self.btn_panel_color.setText(_translate("setPanelInfo", "请选择颜色"))
        self.panel_model_4.setText(_translate("setPanelInfo", "组件海拔:"))
        self.panel_model_7.setText(_translate("setPanelInfo", "组件厂家:"))
