# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_panel_info_new.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_set_panel_info_new(object):
    def setupUi(self, set_panel_info_new):
        set_panel_info_new.setObjectName("set_panel_info_new")
        set_panel_info_new.resize(500, 600)
        self.panel_tab = QtWidgets.QTabWidget(set_panel_info_new)
        self.panel_tab.setGeometry(QtCore.QRect(0, 0, 501, 601))
        self.panel_tab.setObjectName("panel_tab")
        self.old_Template = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(15)
        self.old_Template.setFont(font)
        self.old_Template.setObjectName("old_Template")
        self.old_panel_angle = QtWidgets.QLineEdit(self.old_Template)
        self.old_panel_angle.setEnabled(False)
        self.old_panel_angle.setGeometry(QtCore.QRect(160, 330, 251, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.old_panel_angle.setFont(font)
        self.old_panel_angle.setObjectName("old_panel_angle")
        self.panel_model_9 = QtWidgets.QLabel(self.old_Template)
        self.panel_model_9.setGeometry(QtCore.QRect(30, 180, 80, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.panel_model_9.setFont(font)
        self.panel_model_9.setObjectName("panel_model_9")
        self.old_label_manufactor = QtWidgets.QLineEdit(self.old_Template)
        self.old_label_manufactor.setEnabled(False)
        self.old_label_manufactor.setGeometry(QtCore.QRect(160, 130, 251, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.old_label_manufactor.setFont(font)
        self.old_label_manufactor.setObjectName("old_label_manufactor")
        self.old_panel_wh = QtWidgets.QLineEdit(self.old_Template)
        self.old_panel_wh.setEnabled(False)
        self.old_panel_wh.setGeometry(QtCore.QRect(160, 230, 251, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.old_panel_wh.setFont(font)
        self.old_panel_wh.setObjectName("old_panel_wh")
        self.old_panel_altitude = QtWidgets.QLineEdit(self.old_Template)
        self.old_panel_altitude.setEnabled(False)
        self.old_panel_altitude.setGeometry(QtCore.QRect(160, 280, 251, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.old_panel_altitude.setFont(font)
        self.old_panel_altitude.setObjectName("old_panel_altitude")
        self.panel_model_10 = QtWidgets.QLabel(self.old_Template)
        self.panel_model_10.setGeometry(QtCore.QRect(30, 330, 80, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.panel_model_10.setFont(font)
        self.panel_model_10.setObjectName("panel_model_10")
        self.panel_model_11 = QtWidgets.QLabel(self.old_Template)
        self.panel_model_11.setGeometry(QtCore.QRect(30, 80, 80, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.panel_model_11.setFont(font)
        self.panel_model_11.setObjectName("panel_model_11")
        self.old_label_type = QtWidgets.QLineEdit(self.old_Template)
        self.old_label_type.setEnabled(False)
        self.old_label_type.setGeometry(QtCore.QRect(160, 80, 251, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.old_label_type.setFont(font)
        self.old_label_type.setObjectName("old_label_type")
        self.panel_model_12 = QtWidgets.QLabel(self.old_Template)
        self.panel_model_12.setGeometry(QtCore.QRect(30, 280, 80, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.panel_model_12.setFont(font)
        self.panel_model_12.setObjectName("panel_model_12")
        self.panel_model_13 = QtWidgets.QLabel(self.old_Template)
        self.panel_model_13.setGeometry(QtCore.QRect(30, 380, 80, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.panel_model_13.setFont(font)
        self.panel_model_13.setObjectName("panel_model_13")
        self.old_panel_power = QtWidgets.QLineEdit(self.old_Template)
        self.old_panel_power.setEnabled(False)
        self.old_panel_power.setGeometry(QtCore.QRect(160, 180, 251, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.old_panel_power.setFont(font)
        self.old_panel_power.setObjectName("old_panel_power")
        self.old_panel_arrange = QtWidgets.QLineEdit(self.old_Template)
        self.old_panel_arrange.setEnabled(False)
        self.old_panel_arrange.setGeometry(QtCore.QRect(160, 380, 251, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.old_panel_arrange.setFont(font)
        self.old_panel_arrange.setObjectName("old_panel_arrange")
        self.panel_model_15 = QtWidgets.QLabel(self.old_Template)
        self.panel_model_15.setGeometry(QtCore.QRect(30, 130, 80, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.panel_model_15.setFont(font)
        self.panel_model_15.setObjectName("panel_model_15")
        self.panel_model_16 = QtWidgets.QLabel(self.old_Template)
        self.panel_model_16.setGeometry(QtCore.QRect(30, 230, 80, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.panel_model_16.setFont(font)
        self.panel_model_16.setObjectName("panel_model_16")
        self.panel_model_17 = QtWidgets.QLabel(self.old_Template)
        self.panel_model_17.setGeometry(QtCore.QRect(30, 30, 80, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.panel_model_17.setFont(font)
        self.panel_model_17.setObjectName("panel_model_17")
        self.old_panel_model = QtWidgets.QComboBox(self.old_Template)
        self.old_panel_model.setGeometry(QtCore.QRect(160, 30, 251, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.old_panel_model.setFont(font)
        self.old_panel_model.setObjectName("old_panel_model")
        self.btu_old_close = QtWidgets.QPushButton(self.old_Template)
        self.btu_old_close.setGeometry(QtCore.QRect(280, 520, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btu_old_close.setFont(font)
        self.btu_old_close.setObjectName("btu_old_close")
        self.but_old_save = QtWidgets.QPushButton(self.old_Template)
        self.but_old_save.setGeometry(QtCore.QRect(120, 520, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.but_old_save.setFont(font)
        self.but_old_save.setObjectName("but_old_save")
        self.panel_model_20 = QtWidgets.QLabel(self.old_Template)
        self.panel_model_20.setGeometry(QtCore.QRect(30, 430, 80, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.panel_model_20.setFont(font)
        self.panel_model_20.setObjectName("panel_model_20")
        self.old_color_widget = QtWidgets.QWidget(self.old_Template)
        self.old_color_widget.setGeometry(QtCore.QRect(160, 430, 121, 25))
        self.old_color_widget.setObjectName("old_color_widget")
        self.panel_tab.addTab(self.old_Template, "")
        self.new_Template = QtWidgets.QWidget()
        self.new_Template.setObjectName("new_Template")
        self.new_panel_angle = QtWidgets.QLineEdit(self.new_Template)
        self.new_panel_angle.setGeometry(QtCore.QRect(160, 330, 251, 25))
        self.new_panel_angle.setObjectName("new_panel_angle")
        self.panel_model_2 = QtWidgets.QLabel(self.new_Template)
        self.panel_model_2.setGeometry(QtCore.QRect(20, 180, 80, 21))
        self.panel_model_2.setObjectName("panel_model_2")
        self.new_label_manufactor = QtWidgets.QLineEdit(self.new_Template)
        self.new_label_manufactor.setGeometry(QtCore.QRect(160, 130, 251, 25))
        self.new_label_manufactor.setObjectName("new_label_manufactor")
        self.new_panel_wh = QtWidgets.QLineEdit(self.new_Template)
        self.new_panel_wh.setGeometry(QtCore.QRect(160, 230, 251, 25))
        self.new_panel_wh.setObjectName("new_panel_wh")
        self.new_panel_altitude = QtWidgets.QLineEdit(self.new_Template)
        self.new_panel_altitude.setGeometry(QtCore.QRect(160, 280, 251, 25))
        self.new_panel_altitude.setObjectName("new_panel_altitude")
        self.btu_new_close = QtWidgets.QPushButton(self.new_Template)
        self.btu_new_close.setGeometry(QtCore.QRect(270, 490, 93, 28))
        self.btu_new_close.setObjectName("btu_new_close")
        self.panel_model_5 = QtWidgets.QLabel(self.new_Template)
        self.panel_model_5.setGeometry(QtCore.QRect(20, 330, 80, 21))
        self.panel_model_5.setObjectName("panel_model_5")
        self.panel_model_6 = QtWidgets.QLabel(self.new_Template)
        self.panel_model_6.setGeometry(QtCore.QRect(20, 80, 80, 21))
        self.panel_model_6.setObjectName("panel_model_6")
        self.panel_model_4 = QtWidgets.QLabel(self.new_Template)
        self.panel_model_4.setGeometry(QtCore.QRect(20, 280, 80, 21))
        self.panel_model_4.setObjectName("panel_model_4")
        self.panel_model_8 = QtWidgets.QLabel(self.new_Template)
        self.panel_model_8.setGeometry(QtCore.QRect(20, 380, 80, 21))
        self.panel_model_8.setObjectName("panel_model_8")
        self.new_panel_power = QtWidgets.QLineEdit(self.new_Template)
        self.new_panel_power.setGeometry(QtCore.QRect(160, 180, 251, 25))
        self.new_panel_power.setObjectName("new_panel_power")
        self.new_panel_arrange = QtWidgets.QLineEdit(self.new_Template)
        self.new_panel_arrange.setGeometry(QtCore.QRect(160, 380, 251, 25))
        self.new_panel_arrange.setObjectName("new_panel_arrange")
        self.panel_model_7 = QtWidgets.QLabel(self.new_Template)
        self.panel_model_7.setGeometry(QtCore.QRect(20, 130, 80, 21))
        self.panel_model_7.setObjectName("panel_model_7")
        self.but_new_save = QtWidgets.QPushButton(self.new_Template)
        self.but_new_save.setGeometry(QtCore.QRect(110, 490, 93, 28))
        self.but_new_save.setObjectName("but_new_save")
        self.panel_model_3 = QtWidgets.QLabel(self.new_Template)
        self.panel_model_3.setGeometry(QtCore.QRect(20, 230, 80, 21))
        self.panel_model_3.setObjectName("panel_model_3")
        self.panel_model_18 = QtWidgets.QLabel(self.new_Template)
        self.panel_model_18.setGeometry(QtCore.QRect(20, 30, 80, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.panel_model_18.setFont(font)
        self.panel_model_18.setObjectName("panel_model_18")
        self.new_panel_model = QtWidgets.QLineEdit(self.new_Template)
        self.new_panel_model.setGeometry(QtCore.QRect(160, 30, 251, 25))
        self.new_panel_model.setObjectName("new_panel_model")
        self.panel_model_19 = QtWidgets.QLabel(self.new_Template)
        self.panel_model_19.setGeometry(QtCore.QRect(20, 430, 80, 21))
        self.panel_model_19.setObjectName("panel_model_19")
        self.btn_panel_color = QtWidgets.QPushButton(self.new_Template)
        self.btn_panel_color.setGeometry(QtCore.QRect(160, 430, 150, 25))
        self.btn_panel_color.setObjectName("btn_panel_color")
        self.new_panel_color = QtWidgets.QWidget(self.new_Template)
        self.new_panel_color.setGeometry(QtCore.QRect(320, 430, 91, 25))
        self.new_panel_color.setStyleSheet("background-color: rgb(0,255, 0)")
        self.new_panel_color.setObjectName("new_panel_color")
        self.new_label_type = QtWidgets.QComboBox(self.new_Template)
        self.new_label_type.setGeometry(QtCore.QRect(160, 80, 251, 25))
        self.new_label_type.setObjectName("new_label_type")
        self.panel_tab.addTab(self.new_Template, "")
        self.setWindowModality(QtCore.Qt.ApplicationModal)
        self.retranslateUi(set_panel_info_new)
        self.panel_tab.setCurrentIndex(1)
        self.btu_old_close.clicked.connect(set_panel_info_new.close)
        self.btu_new_close.clicked.connect(set_panel_info_new.close)
        QtCore.QMetaObject.connectSlotsByName(set_panel_info_new)


    def retranslateUi(self, set_panel_info_new):
        _translate = QtCore.QCoreApplication.translate
        set_panel_info_new.setWindowTitle(_translate("set_panel_info_new", "设置组件信息"))
        self.panel_model_9.setText(_translate("set_panel_info_new", "组件功率:"))
        self.panel_model_10.setText(_translate("set_panel_info_new", "组件角度:"))
        self.panel_model_11.setText(_translate("set_panel_info_new", "标注类型:"))
        self.panel_model_12.setText(_translate("set_panel_info_new", "组件海拔:"))
        self.panel_model_13.setText(_translate("set_panel_info_new", "组件排布:"))
        self.panel_model_15.setText(_translate("set_panel_info_new", "组件厂家:"))
        self.panel_model_16.setText(_translate("set_panel_info_new", "组件宽高:"))
        self.panel_model_17.setText(_translate("set_panel_info_new", "组件型号:"))
        self.btu_old_close.setText(_translate("set_panel_info_new", "取消"))
        self.but_old_save.setText(_translate("set_panel_info_new", "确定"))
        self.panel_model_20.setText(_translate("set_panel_info_new", "选择颜色:"))
        self.panel_tab.setTabText(self.panel_tab.indexOf(self.old_Template), _translate("set_panel_info_new", "已有模板"))
        self.panel_model_2.setText(_translate("set_panel_info_new", "组件功率:"))
        self.btu_new_close.setText(_translate("set_panel_info_new", "取消"))
        self.panel_model_5.setText(_translate("set_panel_info_new", "组件角度:"))
        self.panel_model_6.setText(_translate("set_panel_info_new", "标注类型:"))
        self.panel_model_4.setText(_translate("set_panel_info_new", "组件海拔:"))
        self.panel_model_8.setText(_translate("set_panel_info_new", "组件排布:"))
        self.panel_model_7.setText(_translate("set_panel_info_new", "组件厂家:"))
        self.but_new_save.setText(_translate("set_panel_info_new", "保存"))
        self.panel_model_3.setText(_translate("set_panel_info_new", "组件宽高:"))
        self.panel_model_18.setText(_translate("set_panel_info_new", "组件型号:"))
        self.panel_model_19.setText(_translate("set_panel_info_new", "选择颜色:"))
        self.btn_panel_color.setText(_translate("set_panel_info_new", "请选择颜色"))
        self.panel_tab.setTabText(self.panel_tab.indexOf(self.new_Template), _translate("set_panel_info_new", "新建模板"))
