# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\pythonWork\RGIS\UI\RGISMainActivity.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RGISMain(object):
    def setupUi(self, RGISMain):
        RGISMain.setObjectName("RGISMain")
        RGISMain.resize(1308, 937)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RGISMain.sizePolicy().hasHeightForWidth())
        RGISMain.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(RGISMain)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")


        self.PlanName = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlanName.sizePolicy().hasHeightForWidth())
        self.PlanName.setSizePolicy(sizePolicy)
        self.PlanName.setMaximumSize(QtCore.QSize(151, 16777215))
        self.PlanName.setAlignment(QtCore.Qt.AlignCenter)
        self.PlanName.setWordWrap(True)
        self.PlanName.setObjectName("PlanName")
        self.verticalLayout.addWidget(self.PlanName)
        self.listPanelID = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listPanelID.sizePolicy().hasHeightForWidth())
        self.listPanelID.setSizePolicy(sizePolicy)
        self.listPanelID.setMinimumSize(QtCore.QSize(151, 621))
        self.listPanelID.setMaximumSize(QtCore.QSize(151, 16777215))
        self.listPanelID.setObjectName("listPanelID")
        self.verticalLayout.addWidget(self.listPanelID)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lab_projectName = QtWidgets.QLabel(self.centralwidget)
        self.lab_projectName.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_projectName.setObjectName("lab_projectName")
        self.verticalLayout_2.addWidget(self.lab_projectName)
        self.MapImage = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MapImage.sizePolicy().hasHeightForWidth())
        self.MapImage.setSizePolicy(sizePolicy)
        self.MapImage.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.MapImage.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.MapImage.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.MapImage.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.MapImage.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.MapImage.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.MapImage.setCacheMode(QtWidgets.QGraphicsView.CacheNone)
        self.MapImage.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorViewCenter)
        self.MapImage.setResizeAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.MapImage.setViewportUpdateMode(QtWidgets.QGraphicsView.BoundingRectViewportUpdate)
        self.MapImage.setRubberBandSelectionMode(QtCore.Qt.IntersectsItemShape)
        self.MapImage.setObjectName("MapImage")
        self.verticalLayout_2.addWidget(self.MapImage)
        self.te_bottom_hint = QtWidgets.QTextEdit(self.centralwidget)
        self.te_bottom_hint.setMaximumSize(QtCore.QSize(16777215, 80))
        self.te_bottom_hint.setObjectName("te_bottom_hint")
        self.verticalLayout_2.addWidget(self.te_bottom_hint)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        #工具箱
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(140, 0))
        self.groupBox.setObjectName("groupBox")

        self.button_layout = QtWidgets.QVBoxLayout(self.groupBox)
        # self.button_layout.setContentsMargins(0, 0, 0, 0)
        self.button_layout.setObjectName("button_layout")
        #组件模板
        self.panel_mode_Box= QtWidgets.QGroupBox(self.centralwidget)
        self.panel_mode_Box.setMinimumSize(QtCore.QSize(140, 0))
        self.panel_mode_Box.setObjectName("panel_mode_Box")

        self.mode_button_layout = QtWidgets.QVBoxLayout(self.panel_mode_Box)
        # self.button_layout.setContentsMargins(0, 0, 0, 0)
        self.mode_button_layout.setObjectName("mode_button_layout")

        #组件标注
        self.panel_bz_Box= QtWidgets.QGroupBox(self.centralwidget)
        self.panel_bz_Box.setMinimumSize(QtCore.QSize(140, 0))
        self.panel_bz_Box.setObjectName("panel_bz_Box")

        self.bz_button_layout = QtWidgets.QVBoxLayout(self.panel_bz_Box)
        # self.button_layout.setContentsMargins(0, 0, 0, 0)
        self.bz_button_layout.setObjectName("bz_button_layout")
        #组件编辑
        self.panel_edit_Box= QtWidgets.QGroupBox(self.centralwidget)
        self.panel_edit_Box.setMinimumSize(QtCore.QSize(140, 0))
        self.panel_edit_Box.setObjectName("panel_edit_Box")

        self.edit_button_layout = QtWidgets.QVBoxLayout(self.panel_edit_Box)
        # self.button_layout.setContentsMargins(0, 0, 0, 0)
        self.edit_button_layout.setObjectName("edit_button_layout")
        #GPS修改
        self.gps_Box= QtWidgets.QGroupBox(self.centralwidget)
        self.gps_Box.setMinimumSize(QtCore.QSize(140, 0))
        self.gps_Box.setObjectName("panel_edit_Box")
        self.gps_button_layout = QtWidgets.QVBoxLayout(self.gps_Box)
        # self.button_layout.setContentsMargins(0, 0, 0, 0)
        self.gps_button_layout.setObjectName("gps_button_layout")



        self.grid_layout = QtWidgets.QGridLayout()
        self.grid_layout.setObjectName("grid_layout")



        self.but_zoomout = QtWidgets.QPushButton()
        #self.but_zoomout.setGeometry(QtCore.QRect(10, 50, 60, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_zoomout.sizePolicy().hasHeightForWidth())
        self.but_zoomout.setSizePolicy(sizePolicy)
        self.but_zoomout.setMaximumSize(QtCore.QSize(60, 30))
        self.but_zoomout.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.but_zoomout.setObjectName("but_zoomout")
        self.but_zoomout.setEnabled(False)
        self.but_movemode = QtWidgets.QPushButton()#self.groupBox
        #self.but_movemode.setGeometry(QtCore.QRect(10, 20, 60, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_movemode.sizePolicy().hasHeightForWidth())
        self.but_movemode.setSizePolicy(sizePolicy)
        self.but_movemode.setMaximumSize(QtCore.QSize(60, 30))
        self.but_movemode.setObjectName("but_movemode")
        self.but_movemode.setEnabled(False)
        self.but_zoomin = QtWidgets.QPushButton()
        #self.but_zoomin.setGeometry(QtCore.QRect(70, 50, 60, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_zoomin.sizePolicy().hasHeightForWidth())
        self.but_zoomin.setSizePolicy(sizePolicy)
        self.but_zoomin.setMaximumSize(QtCore.QSize(60, 30))
        self.but_zoomin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.but_zoomin.setObjectName("but_zoomin")
        self.but_zoomin.setEnabled(False)
        self.but_rest = QtWidgets.QPushButton()
        #self.but_rest.setGeometry(QtCore.QRect(70, 20, 60, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_rest.sizePolicy().hasHeightForWidth())
        self.but_rest.setSizePolicy(sizePolicy)
        self.but_rest.setMaximumSize(QtCore.QSize(60, 30))
        self.but_rest.setObjectName("but_rest")
        self.but_rest.setEnabled(False)

        self.grid_layout.addWidget(self.but_movemode, 1, 0)#固定
        self.grid_layout.addWidget(self.but_rest, 1, 1)#刷新
        self.grid_layout.addWidget(self.but_zoomout, 2, 0)#放大
        self.grid_layout.addWidget(self.but_zoomin, 2, 1)#缩小
        self.button_layout.addLayout(self.grid_layout)

        self.but_setpanel_info = QtWidgets.QPushButton()
        #self.but_setpanel_info.setGeometry(QtCore.QRect(10, 100, 120, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_setpanel_info.sizePolicy().hasHeightForWidth())
        self.but_setpanel_info.setSizePolicy(sizePolicy)
        self.but_setpanel_info.setMaximumSize(QtCore.QSize(120, 30))
        self.but_setpanel_info.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.but_setpanel_info.setObjectName("but_setpanel_info")
        self.but_setpanel_info.setEnabled(False)
        self.button_layout.addWidget(self.but_setpanel_info)

        self.cb_label_mode = QtWidgets.QComboBox()
        #self.cb_label_mode.setGeometry(QtCore.QRect(10, 380, 121, 22))
        self.cb_label_mode.setEditable(False)
        self.cb_label_mode.setCurrentText("")
        self.cb_label_mode.setObjectName("cb_label_mode")

        self.but_update_panel_mode = QtWidgets.QPushButton()
        #self.but_setpanel_info.setGeometry(QtCore.QRect(10, 100, 120, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_update_panel_mode.sizePolicy().hasHeightForWidth())
        self.but_update_panel_mode.setSizePolicy(sizePolicy)
        self.but_update_panel_mode.setMaximumSize(QtCore.QSize(120, 30))
        self.but_update_panel_mode.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.but_update_panel_mode.setObjectName("but_update_panel_mode")
        self.but_update_panel_mode.setEnabled(False)
        self.button_layout.addWidget(self.but_update_panel_mode)

        self.but_delete_panel_mode = QtWidgets.QPushButton()
        # self.but_setpanel_info.setGeometry(QtCore.QRect(10, 100, 120, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_delete_panel_mode.sizePolicy().hasHeightForWidth())
        self.but_delete_panel_mode.setSizePolicy(sizePolicy)
        self.but_delete_panel_mode.setMaximumSize(QtCore.QSize(120, 30))
        self.but_delete_panel_mode.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.but_delete_panel_mode.setObjectName("but_delete_panel_mode")
        self.but_delete_panel_mode.setEnabled(False)
        self.button_layout.addWidget(self.but_delete_panel_mode)


        self.cb_panel_mode = QtWidgets.QComboBox()
        # self.cb_label_mode.setGeometry(QtCore.QRect(10, 380, 121, 22))
        self.cb_panel_mode.setCurrentText("")
        self.cb_panel_mode.setObjectName("cb_panel_mode")

        self.but_getpanel_wh = QtWidgets.QPushButton()
        #self.but_getpanel_wh.setGeometry(QtCore.QRect(10, 140, 120, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_getpanel_wh.sizePolicy().hasHeightForWidth())
        self.but_getpanel_wh.setSizePolicy(sizePolicy)
        self.but_getpanel_wh.setMaximumSize(QtCore.QSize(120, 30))
        self.but_getpanel_wh.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.but_getpanel_wh.setObjectName("but_getpanel_wh")
        self.but_getpanel_wh.setEnabled(False)
        self.btn_move_panel = QtWidgets.QPushButton()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_move_panel.sizePolicy().hasHeightForWidth())
        self.btn_move_panel.setSizePolicy(sizePolicy)
        self.btn_move_panel.setMaximumSize(QtCore.QSize(120, 30))
        self.btn_move_panel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_move_panel.setObjectName("but_move_panel")
        self.btn_move_panel.setEnabled(False)
        self.btn_move_no = QtWidgets.QPushButton()
        self.btn_move_no.setObjectName("btn_move_no")
        self.btn_move_ok = QtWidgets.QPushButton()
        self.btn_move_ok.setObjectName("btn_move_ok")
        self.btn_update_number = QtWidgets.QPushButton()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_update_number.sizePolicy().hasHeightForWidth())
        self.btn_update_number.setSizePolicy(sizePolicy)
        self.btn_update_number.setMaximumSize(QtCore.QSize(120, 30))
        self.btn_update_number.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_update_number.setObjectName("btn_update_number")
        self.btn_update_number.setEnabled(False)

        self.btn_update_number_no = QtWidgets.QPushButton()
        self.btn_update_number_no.setObjectName("btn_update_number_no")
        self.btn_update_number_ok = QtWidgets.QPushButton()
        self.btn_update_number_ok.setObjectName("btn_update_number_ok")
        self.btn_GPS_computing = QtWidgets.QPushButton()
        self.btn_GPS_computing.setObjectName("btn_GPS_computing")
        self.btn_GPS_computing.setEnabled(False)
        self.btn_GPS_range_computing_cancel = QtWidgets.QPushButton()
        self.btn_GPS_range_computing_cancel.setObjectName("btn_GPS_range_computing_cancel")
        self.btn_GPS_range_computing_ok = QtWidgets.QPushButton()
        self.btn_GPS_range_computing_ok.setObjectName("btn_GPS_range_computing_ok")
        self.btn_GPS_range_computing = QtWidgets.QPushButton()
        self.btn_GPS_range_computing.setObjectName("btn_GPS_range_computing")
        self.btn_GPS_range_computing.setEnabled(False)
        self.btn_GPS_undone_computing = QtWidgets.QPushButton()
        self.btn_GPS_undone_computing.setObjectName("btn_GPS_undone_computing")
        self.btn_GPS_undone_computing.setEnabled(False)
        self.btn_GPS_clear = QtWidgets.QPushButton()
        self.btn_GPS_clear.setObjectName("btn_GPS_clear")
        self.btn_GPS_clear.setEnabled(False)
        self.btn_del_panel = QtWidgets.QPushButton()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_del_panel.sizePolicy().hasHeightForWidth())
        self.btn_del_panel.setSizePolicy(sizePolicy)
        self.btn_del_panel.setMaximumSize(QtCore.QSize(120, 30))
        self.btn_del_panel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_del_panel.setObjectName("btn_del_panel")
        self.btn_del_panel.setEnabled(False)
        self.btn_select_panel_info = QtWidgets.QPushButton()
        self.btn_select_panel_info.setObjectName("btn_select_panel_info")
        self.btn_select_panel_info.setEnabled(False)
        #批量修改
        self.btn_batch_update_panel = QtWidgets.QPushButton()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_batch_update_panel.sizePolicy().hasHeightForWidth())
        self.btn_batch_update_panel.setSizePolicy(sizePolicy)
        self.btn_batch_update_panel.setMaximumSize(QtCore.QSize(120, 30))
        self.btn_batch_update_panel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_batch_update_panel.setObjectName("btn_batch_update_panel")
        self.btn_batch_update_panel.setEnabled(False)
        self.btn_batch_update_no = QtWidgets.QPushButton()
        self.btn_batch_update_no.setObjectName("btn_batch_update_no")
        self.btn_batch_update_ok = QtWidgets.QPushButton()
        self.btn_batch_update_ok.setObjectName("btn_batch_update_ok")

        # 批量删除
        self.btn_batch_del_panel = QtWidgets.QPushButton()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_batch_del_panel.sizePolicy().hasHeightForWidth())
        self.btn_batch_del_panel.setSizePolicy(sizePolicy)
        self.btn_batch_del_panel.setMaximumSize(QtCore.QSize(120, 30))
        self.btn_batch_del_panel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_batch_del_panel.setObjectName("btn_batch_del_panel")
        self.btn_batch_del_panel.setEnabled(False)
        self.btn_batch_del_no = QtWidgets.QPushButton()
        self.btn_batch_del_no.setObjectName("btn_batch_del_no")
        self.btn_batch_del_ok = QtWidgets.QPushButton()
        self.btn_batch_del_ok.setObjectName("btn_batch_del_ok")


        self.mode_button_layout.addWidget(self.cb_panel_mode)#设置组件模板
        self.mode_button_layout.addWidget(self.but_update_panel_mode)  # 修改模板信息
        self.mode_button_layout.addWidget(self.but_delete_panel_mode) #删除模板信息
        self.mode_button_layout.addWidget(self.but_setpanel_info)#获取组件信息
        self.bz_button_layout.addWidget(self.but_getpanel_wh)#获取组件大小
        self.bz_button_layout.addWidget(self.cb_label_mode)  # 查看

        self.edit_button_layout.addWidget(self.btn_del_panel)#删除组件
        self.edit_button_layout.addWidget(self.btn_batch_del_no)  # 取消删除
        self.edit_button_layout.addWidget(self.btn_batch_del_ok)  # 确认删除
        self.edit_button_layout.addWidget(self.btn_batch_del_panel)  # 批量删除

        self.edit_button_layout.addWidget(self.btn_select_panel_info)#修改组件
        self.edit_button_layout.addWidget(self.btn_batch_update_no)  # 取消修改
        self.edit_button_layout.addWidget(self.btn_batch_update_ok)  # 确认修改
        self.edit_button_layout.addWidget(self.btn_batch_update_panel)  # 批量修改

        self.edit_button_layout.addWidget(self.btn_move_no)  # 取消移动
        self.edit_button_layout.addWidget(self.btn_move_ok)  # 确定移动
        self.edit_button_layout.addWidget(self.btn_move_panel)  # 组件移动

        self.edit_button_layout.addWidget(self.btn_update_number_no)#取消修改编号
        self.edit_button_layout.addWidget(self.btn_update_number_ok)#确认修改编号
        self.edit_button_layout.addWidget(self.btn_update_number)  # 重新编号

        self.gps_button_layout.addWidget(self.btn_GPS_computing)#GPS计算
        self.gps_button_layout.addWidget(self.btn_GPS_range_computing_ok)#确认计算
        self.gps_button_layout.addWidget(self.btn_GPS_range_computing_cancel)#取消计算
        self.gps_button_layout.addWidget(self.btn_GPS_range_computing)#GPS区域计算
        self.gps_button_layout.addWidget(self.btn_GPS_undone_computing)#GPS撤消
        self.gps_button_layout.addWidget(self.btn_GPS_clear)#GPS清除


        self.verticalLayout_3.addWidget(self.groupBox)
        self.verticalLayout_3.addWidget(self.panel_mode_Box)
        self.verticalLayout_3.addWidget(self.panel_bz_Box)
        self.verticalLayout_3.addWidget(self.panel_edit_Box)
        self.verticalLayout_3.addWidget(self.gps_Box)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        RGISMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RGISMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1308, 23))
        self.menubar.setObjectName("menubar")
        self.menu66 = QtWidgets.QMenu(self.menubar)
        self.menu66.setObjectName("menu66")
        self.menu77 = QtWidgets.QMenu(self.menubar)
        self.menu77.setObjectName("menu77")
        self.menu88 = QtWidgets.QMenu(self.menubar)
        self.menu88.setObjectName("menu88")
        RGISMain.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(RGISMain)
        self.statusbar.setObjectName("statusbar")
        RGISMain.setStatusBar(self.statusbar)
        self.action_create_project = QtWidgets.QAction(RGISMain)
        self.action_create_project.setObjectName("action_create_project")
        self.action_history_project = QtWidgets.QAction(RGISMain)

        self.action_history_project.setObjectName("action_history_project")
        self.action_export_GPS_image = QtWidgets.QAction(RGISMain)
        self.action_export_GPS_image.setObjectName("action_export_GPS_image")
        self.action_import_GPS_image = QtWidgets.QAction(RGISMain)
        self.action_import_GPS_image.setObjectName("action_import_GPS_image")
        self.action_gd_map = QtWidgets.QAction(RGISMain)
        self.action_gd_map.setObjectName("action_gd_map")
        self.action_export_word = QtWidgets.QAction(RGISMain)
        self.action_export_word.setObjectName("action_export_word")
        self.action_chain_table = QtWidgets.QAction(RGISMain)
        self.action_chain_table.setObjectName("action_chain_table")
        self.menu66.addAction(self.action_create_project)
        self.menu66.addAction(self.action_history_project)
        self.menu77.addAction(self.action_export_GPS_image)
        self.menu77.addAction(self.action_import_GPS_image)
        self.menu77.addAction(self.action_gd_map)
        self.menu77.addAction(self.action_export_word)
        self.menu88.addAction(self.action_chain_table)

        self.menubar.addAction(self.menu66.menuAction())
        self.menubar.addAction(self.menu77.menuAction())
        self.menubar.addAction(self.menu88.menuAction())
        #self.menu77.addAction()

        self.retranslateUi(RGISMain)
        QtCore.QMetaObject.connectSlotsByName(RGISMain)

    def retranslateUi(self, RGISMain):
        _translate = QtCore.QCoreApplication.translate
        RGISMain.setWindowTitle(_translate("RGISMain", "地理信息标注系统"))
        self.PlanName.setText(_translate("RGISMain", "面板列表"))
        self.lab_projectName.setText(_translate("RGISMain", "大地图"))
        self.groupBox.setTitle(_translate("RGISMain", "工具箱"))
        self.panel_mode_Box.setTitle(_translate("RGISMain", "组件模板"))
        self.panel_bz_Box.setTitle(_translate("RGISMain", "组件标注"))
        self.panel_edit_Box.setTitle(_translate("RGISMain", "组件编辑"))
        self.gps_Box.setTitle(_translate("RGISMain", "GPS修改"))
        self.but_zoomout.setToolTip(_translate("RGISMain", "快捷键P"))
        self.but_zoomout.setText(_translate("RGISMain", "放大"))
        self.but_movemode.setToolTip(_translate("RGISMain", "快捷键F"))
        self.but_movemode.setText(_translate("RGISMain", "固定"))
        self.but_zoomin.setToolTip(_translate("RGISMain", "快捷键O"))
        self.but_zoomin.setText(_translate("RGISMain", "缩小"))
        self.but_rest.setToolTip(_translate("RGISMain", "快捷键I"))
        self.but_rest.setText(_translate("RGISMain", "刷新"))
        self.but_update_panel_mode.setToolTip(_translate("RGISMain","快捷键M"))
        self.but_update_panel_mode.setText(_translate("RGISMain","修改模板信息"))
        self.but_delete_panel_mode.setText(_translate("RGISMain","删除模板信息"))
        self.but_setpanel_info.setToolTip(_translate("RGISMain", "快捷键H"))
        self.but_setpanel_info.setText(_translate("RGISMain", "添加模板信息"))
        self.but_getpanel_wh.setToolTip(_translate("RGISMain", "快捷键G"))
        self.but_getpanel_wh.setText(_translate("RGISMain", "获取组件大小"))
        self.btn_move_panel.setToolTip(_translate("RGISMain", "快捷键M"))
        self.btn_move_panel.setText(_translate("RGISMain", "移动组件"))
        self.btn_move_no.setToolTip(_translate("RGISMain", "快捷键Esc"))
        self.btn_move_no.setText(_translate("RGISMain", "取消移动"))
        self.btn_move_ok.setText(_translate("RGISMain", "确认移动"))
        self.btn_update_number.setToolTip(_translate("RGISMain", "快捷键L"))
        self.btn_update_number_no.setText(_translate("RGISMain", "取消修改编号"))
        self.btn_update_number_ok.setText(_translate("RGISMain", "确认修改编号"))
        self.btn_update_number.setText(_translate("RGISMain", "重新编号"))
        self.btn_GPS_computing.setText(_translate("RGISMain", "GPS计算"))
        self.btn_GPS_range_computing_ok.setText(_translate("RGISMain", "确认GPS区域计算"))
        self.btn_GPS_range_computing_cancel.setText(_translate("RGISMain", "取消GPS区域计算"))
        self.btn_GPS_range_computing.setText(_translate("RGISMain","GPS区域计算"))
        self.btn_GPS_undone_computing.setText(_translate("RGISMain", "GPS撤消计算"))
        self.btn_GPS_clear.setText(_translate("RGISMain", "GPS清除"))
        self.btn_del_panel.setToolTip(_translate("RGISMain", "快捷键del"))
        self.btn_del_panel.setText(_translate("RGISMain", "删除组件"))
        self.btn_select_panel_info.setToolTip(_translate("RGISMain", "快捷键U"))
        self.btn_select_panel_info.setText(_translate("RGISMain", "修改组件"))
        self.btn_batch_update_panel.setText(_translate("RGISMain", "批量修改"))
        self.btn_batch_update_no.setText(_translate("RGISMain", "取消修改"))
        self.btn_batch_update_ok.setText(_translate("RGISMain", "确认修改"))
        self.btn_batch_del_panel.setText(_translate("RGISMain", "批量删除"))
        self.btn_batch_del_no.setText(_translate("RGISMain", "取消删除"))
        self.btn_batch_del_ok.setText(_translate("RGISMain", "确认删除"))
        self.menu66.setTitle(_translate("RGISMain", "开始"))
        self.menu77.setTitle(_translate("RGISMain", "操作"))
        self.menu88.setTitle(_translate("RGISMain","上传"))
        self.action_create_project.setText(_translate("RGISMain", "新建项目"))
        self.action_history_project.setText(_translate("RGISMain", "历史项目"))
        self.action_export_GPS_image.setText(_translate("RGISMain", "导出GPS\全景图"))
        self.action_import_GPS_image.setText(_translate("RGISMain", "导入GPS\全景图"))
        self.action_gd_map.setText(_translate("RGISMain", "google地图显示"))
        self.action_export_word.setText(_translate("RIGSMain","导出word文档"))
        self.action_chain_table.setText(_translate("RIGSMain","区块链操作"))
